apiVersion: v1
kind: Service
metadata:
  name: fictions-api
  namespace: fictions-app
  labels:
    app: fictions-api
spec:
  type: ClusterIP
  selector:
    app: fictions-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http

