apiVersion: v1
kind: Service
metadata:
  name: fictions-frontend
  namespace: fictions-app
  labels:
    app: fictions-frontend
spec:
  type: ClusterIP
  selector:
    app: fictions-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

